### ISSUE TITLE
Create function doesn't work in vosonSML_0.29.4

### ISSUE THREAD

**Issue by ktanaka086** [vosonlab/vosonSML#33]
Hi there,
When I use the version 0.29.4, `Create` doesn't generate a network object (i.e., NULL). It seems this's true regardless of OS (e.g., Windows, Mac, and Linux) and different versions of R (e.g., 3.5 and 3.6). This isn't an issue on the version 0.27.2 if I do the same thing (i.e., collecting data and then generating a network using `Create`).

**Comment by mishoryu** [comment]
Thanks for posting this issue. I was wondering if I could please get a few more details about the problem so that I can reproduce it. What type of network are you trying to create and from which social media was it collected? Was the data from `Collect` from the same version as used in `Create`?

There was also a major change in the workflow in version 0.29 in which `Create` produces a list of two dataframes `nodes` and `edges` instead of an `igraph` object as previous versions. The graph creation was moved to a subsequent function named `Graph`. Could this explain the issue?

**Comment by ktanaka086** [comment]
Thank you for your response! I didn't realize that there was a change that requires running `Graph`. That solves the issue.
FYI, yes I collected the data from `Collect` and then execute `Create` in the same version. But, I didn't know to convert the data into an `igraph` object, I need to run `Graph`.
Thanks for your help!
