### ISSUE TITLE
Error in gsub(sprintf("(*UCP)\\b(%s)\\b", paste(sort(words, decreasing = TRUE),  :    invalid regular expression

### ISSUE THREAD

**Issue by zkharazian** [vosonlab/vosonSML#35]
Collected tweets using the rtweet package. Now trying to generate a Twitter semantic network. Was able to generate an actor network with no problem. 

Error now occurs after running
`semanticNetwork <- twitterData %>% 
                   Create("semantic", removeTermsOrHashtags = c("#auspol"), termFreq = 2,
                          hashtagFreq = 10, verbose = TRUE)
`

**Comment by mishoryu** [comment]
Thanks for posting this error. It doesn't appear to be an error thrown by `vosonSML` but instead one of the packages it uses to perform text analysis. I performed a quick search and found some references to the problem on stackoverflow with the `tm` package and removing stopwords. 

Unfortunately I haven't been able to reproduce the issue and as I can't see a problem with your `removeTermsOrHashtags` list, I think it may be due to some problematic data for `tm`.

The latest version of `vosonSML` v0.29.10 uses a different approach and text package (`tidytext`) to create twitter semantic networks. Would it be possible to try it out and see if it resolves the problem?
