### ISSUE TITLE
2-mode network error

### ISSUE THREAD

**Issue by ruyhliu** [vosonlab/vosonSML#42]
When running the example, there were errors:

> twomodeNetwork <- twitterData %>% Create("twomode", removeTermsOrHashtags = c("#auspol"))
Generating twitter 2-mode network...**Using `to_lower = TRUE` with `token = 'tweets'` may not preserve URLs.**
Done.

> twomodeNetwork
 Network attributes:
**Error in if (names(x$gal)[i] == "n") { : argument is of length zero**

Are the errors thrown by vosonSML or other packages? Thanks!

**Comment by mishoryu** [comment]
Thanks for posting this issue. This specific error isn't generated by vosonSML so it is likely from a package in its dependency chain. I'm not sure which one at this stage. Unfortunately I haven't been able to duplicate it so that suggests it is a problem caused by processing something in the data, perhaps during tokenisation or perhaps some dependency package version being different.

Does this error occur for you consistently and are your packages all updated?

**Comment by ruyhliu** [comment]
Thanks for attending to the matter. It helps. Thanks!
