### ISSUE TITLE
Allow youtube search queries

### ISSUE THREAD

**Issue by Fergus-Boyd** [vosonlab/vosonSML#6]
I'm planning on using this package for a project I'm working on. I need to first write a function that will return a vector of all video IDs that match my search parameters (so that I can then use them with CollectDataYoutube()). If I created this function and submitted a pull request, would you be interested in accepting?

**Comment by mishoryu** [comment]
That would be a great feature and is something we've considered implementing to bring it in line with twitter and future reddit search functionality. However, please note that the package will be undergoing a fairly active development phase over the coming months. In terms of youtube changes we will probably be moving towards incorporating existing youtube R packages that already have search functions and replacing our current implementation. This is because at this time we would like the to focus more on data wrangling and network creation for analysis rather than maintaining data collectors.  

Unfortunately I can’t give you a development timeline so it’s probably best to proceed with your own plans, but please be mindful of the above if you are considering contributing.
